# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_client.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import saas.input_client.service.input_client_pb2 as input__client__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_client.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12model_client.proto\x1a\x12input_client.proto\"P\n\tModelInfo\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x1b\n\x13intermediate_output\x18\x02 \x01(\t\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\"5\n\x12ModelBinarySklearn\x12\x0b\n\x03\x62in\x18\x01 \x01(\x0c\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\"c\n\x10ModelBinaryKeras\x12\x0e\n\x06\x63onfig\x18\x01 \x01(\x0c\x12\x0f\n\x07weights\x18\x02 \x01(\x0c\x12\x11\n\ttype_info\x18\x03 \x01(\t\x12\x1b\n\x13intermediate_output\x18\x04 \x01(\t2\xe5\x02\n\x0bModelClient\x12\x38\n\x15transfer_enc_services\x12\x13.EncServicesEncoded\x1a\x08.NoParam\"\x00\x12%\n\x0cupload_model\x12\t.BinModel\x1a\x08.NoParam\"\x00\x12\x35\n\x1b\x63ompile_model_from_local_h5\x12\n.ModelInfo\x1a\x08.NoParam\"\x00\x12\x36\n\x1c\x63ompile_model_from_local_pkl\x12\n.ModelInfo\x1a\x08.NoParam\"\x00\x12\x44\n!compile_model_from_binary_sklearn\x12\x13.ModelBinarySklearn\x1a\x08.NoParam\"\x00\x12@\n\x1f\x63ompile_model_from_binary_keras\x12\x11.ModelBinaryKeras\x1a\x08.NoParam\"\x00\x62\x06proto3'
  ,
  dependencies=[input__client__pb2.DESCRIPTOR,])




_MODELINFO = _descriptor.Descriptor(
  name='ModelInfo',
  full_name='ModelInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_name', full_name='ModelInfo.model_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intermediate_output', full_name='ModelInfo.intermediate_output', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='ModelInfo.batch_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=122,
)


_MODELBINARYSKLEARN = _descriptor.Descriptor(
  name='ModelBinarySklearn',
  full_name='ModelBinarySklearn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bin', full_name='ModelBinarySklearn.bin', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='ModelBinarySklearn.batch_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=177,
)


_MODELBINARYKERAS = _descriptor.Descriptor(
  name='ModelBinaryKeras',
  full_name='ModelBinaryKeras',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='ModelBinaryKeras.config', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weights', full_name='ModelBinaryKeras.weights', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type_info', full_name='ModelBinaryKeras.type_info', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intermediate_output', full_name='ModelBinaryKeras.intermediate_output', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=278,
)

DESCRIPTOR.message_types_by_name['ModelInfo'] = _MODELINFO
DESCRIPTOR.message_types_by_name['ModelBinarySklearn'] = _MODELBINARYSKLEARN
DESCRIPTOR.message_types_by_name['ModelBinaryKeras'] = _MODELBINARYKERAS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelInfo = _reflection.GeneratedProtocolMessageType('ModelInfo', (_message.Message,), {
  'DESCRIPTOR' : _MODELINFO,
  '__module__' : 'model_client_pb2'
  # @@protoc_insertion_point(class_scope:ModelInfo)
  })
_sym_db.RegisterMessage(ModelInfo)

ModelBinarySklearn = _reflection.GeneratedProtocolMessageType('ModelBinarySklearn', (_message.Message,), {
  'DESCRIPTOR' : _MODELBINARYSKLEARN,
  '__module__' : 'model_client_pb2'
  # @@protoc_insertion_point(class_scope:ModelBinarySklearn)
  })
_sym_db.RegisterMessage(ModelBinarySklearn)

ModelBinaryKeras = _reflection.GeneratedProtocolMessageType('ModelBinaryKeras', (_message.Message,), {
  'DESCRIPTOR' : _MODELBINARYKERAS,
  '__module__' : 'model_client_pb2'
  # @@protoc_insertion_point(class_scope:ModelBinaryKeras)
  })
_sym_db.RegisterMessage(ModelBinaryKeras)



_MODELCLIENT = _descriptor.ServiceDescriptor(
  name='ModelClient',
  full_name='ModelClient',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=281,
  serialized_end=638,
  methods=[
  _descriptor.MethodDescriptor(
    name='transfer_enc_services',
    full_name='ModelClient.transfer_enc_services',
    index=0,
    containing_service=None,
    input_type=input__client__pb2._ENCSERVICESENCODED,
    output_type=input__client__pb2._NOPARAM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='upload_model',
    full_name='ModelClient.upload_model',
    index=1,
    containing_service=None,
    input_type=input__client__pb2._BINMODEL,
    output_type=input__client__pb2._NOPARAM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='compile_model_from_local_h5',
    full_name='ModelClient.compile_model_from_local_h5',
    index=2,
    containing_service=None,
    input_type=_MODELINFO,
    output_type=input__client__pb2._NOPARAM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='compile_model_from_local_pkl',
    full_name='ModelClient.compile_model_from_local_pkl',
    index=3,
    containing_service=None,
    input_type=_MODELINFO,
    output_type=input__client__pb2._NOPARAM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='compile_model_from_binary_sklearn',
    full_name='ModelClient.compile_model_from_binary_sklearn',
    index=4,
    containing_service=None,
    input_type=_MODELBINARYSKLEARN,
    output_type=input__client__pb2._NOPARAM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='compile_model_from_binary_keras',
    full_name='ModelClient.compile_model_from_binary_keras',
    index=5,
    containing_service=None,
    input_type=_MODELBINARYKERAS,
    output_type=input__client__pb2._NOPARAM,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODELCLIENT)

DESCRIPTOR.services_by_name['ModelClient'] = _MODELCLIENT

# @@protoc_insertion_point(module_scope)
