# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: input_client.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='input_client.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12input_client.proto\"\x1f\n\nLocalModel\x12\x11\n\tbin_model\x18\x01 \x01(\x0c\"\t\n\x07NoParam\"W\n\x12\x45ncServicesEncoded\x12\x1f\n\x17\x62\x66v_enc_service_encoded\x18\x01 \x01(\t\x12 \n\x18\x63kks_enc_service_encoded\x18\x02 \x01(\t\"\x16\n\x06Tensor\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1d\n\x08\x42inModel\x12\x11\n\tbin_model\x18\x01 \x01(\x0c\x32t\n\x0bInputClient\x12\x1f\n\x07gen_key\x12\x08.NoParam\x1a\x08.NoParam\"\x00\x12\x1d\n\x07predict\x12\x07.Tensor\x1a\x07.Tensor\"\x00\x12%\n\x0eget_time_stats\x12\x08.NoParam\x1a\x07.Tensor\"\x00\x62\x06proto3'
)




_LOCALMODEL = _descriptor.Descriptor(
  name='LocalModel',
  full_name='LocalModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bin_model', full_name='LocalModel.bin_model', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=53,
)


_NOPARAM = _descriptor.Descriptor(
  name='NoParam',
  full_name='NoParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=64,
)


_ENCSERVICESENCODED = _descriptor.Descriptor(
  name='EncServicesEncoded',
  full_name='EncServicesEncoded',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bfv_enc_service_encoded', full_name='EncServicesEncoded.bfv_enc_service_encoded', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ckks_enc_service_encoded', full_name='EncServicesEncoded.ckks_enc_service_encoded', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=153,
)


_TENSOR = _descriptor.Descriptor(
  name='Tensor',
  full_name='Tensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Tensor.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=177,
)


_BINMODEL = _descriptor.Descriptor(
  name='BinModel',
  full_name='BinModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bin_model', full_name='BinModel.bin_model', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=208,
)

DESCRIPTOR.message_types_by_name['LocalModel'] = _LOCALMODEL
DESCRIPTOR.message_types_by_name['NoParam'] = _NOPARAM
DESCRIPTOR.message_types_by_name['EncServicesEncoded'] = _ENCSERVICESENCODED
DESCRIPTOR.message_types_by_name['Tensor'] = _TENSOR
DESCRIPTOR.message_types_by_name['BinModel'] = _BINMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocalModel = _reflection.GeneratedProtocolMessageType('LocalModel', (_message.Message,), {
  'DESCRIPTOR' : _LOCALMODEL,
  '__module__' : 'input_client_pb2'
  # @@protoc_insertion_point(class_scope:LocalModel)
  })
_sym_db.RegisterMessage(LocalModel)

NoParam = _reflection.GeneratedProtocolMessageType('NoParam', (_message.Message,), {
  'DESCRIPTOR' : _NOPARAM,
  '__module__' : 'input_client_pb2'
  # @@protoc_insertion_point(class_scope:NoParam)
  })
_sym_db.RegisterMessage(NoParam)

EncServicesEncoded = _reflection.GeneratedProtocolMessageType('EncServicesEncoded', (_message.Message,), {
  'DESCRIPTOR' : _ENCSERVICESENCODED,
  '__module__' : 'input_client_pb2'
  # @@protoc_insertion_point(class_scope:EncServicesEncoded)
  })
_sym_db.RegisterMessage(EncServicesEncoded)

Tensor = _reflection.GeneratedProtocolMessageType('Tensor', (_message.Message,), {
  'DESCRIPTOR' : _TENSOR,
  '__module__' : 'input_client_pb2'
  # @@protoc_insertion_point(class_scope:Tensor)
  })
_sym_db.RegisterMessage(Tensor)

BinModel = _reflection.GeneratedProtocolMessageType('BinModel', (_message.Message,), {
  'DESCRIPTOR' : _BINMODEL,
  '__module__' : 'input_client_pb2'
  # @@protoc_insertion_point(class_scope:BinModel)
  })
_sym_db.RegisterMessage(BinModel)



_INPUTCLIENT = _descriptor.ServiceDescriptor(
  name='InputClient',
  full_name='InputClient',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=210,
  serialized_end=326,
  methods=[
  _descriptor.MethodDescriptor(
    name='gen_key',
    full_name='InputClient.gen_key',
    index=0,
    containing_service=None,
    input_type=_NOPARAM,
    output_type=_NOPARAM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='predict',
    full_name='InputClient.predict',
    index=1,
    containing_service=None,
    input_type=_TENSOR,
    output_type=_TENSOR,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_time_stats',
    full_name='InputClient.get_time_stats',
    index=2,
    containing_service=None,
    input_type=_NOPARAM,
    output_type=_TENSOR,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INPUTCLIENT)

DESCRIPTOR.services_by_name['InputClient'] = _INPUTCLIENT

# @@protoc_insertion_point(module_scope)
